### PR TITLE
[dev] PBI AB#114211 [Back Office] Update Service Companion builder to use new Saddleback icons

### PR DESCRIPTION
**Pull request by IlyaRadinsky**
The universal solution to use SVG icons for both `react-native` and `web` apps, based on SVGR (https://react-svgr.com/docs/what-is-svgr/)

Key points:
-
- v1 icons have been kept as is without changes so as not to break the current code
- v2 icons for react-native use the same way (pure SVG files)
- v2 icons for web - are generated React components

How it works:
-
- all SVG files are handled by scripts in `scripts` folder
- at first, all SVG are preparing to use in mobile and stored in `generated/v2/icons`
- generating an index file for them with pretty names (e.g. `baptism-solid.svg` -> `IconBaptismSolid`)
- generating React components by SVG files
- generating an index file for components
- compiling v2 React icon components to the `dist` folder
- copying v1 SVG icons to the `dist` folder

The package is tested:
-
- v1 works on mobile without changes
- v2 works on mobile by the same way as v1
- v2 also tested on web
- tested ability to change color and size on both platform

v1 and v2 on mobile at the same time
-
Screenshot 2024-11-27 at 13 21 58

v2 on web
-
Screenshot 2024-11-27 at 14 13 13

### CODE REVIEW

**Comment by raoufr** [comment]
This is great @IlyaRadinsky Thank you. 
Will review and let you know shortly.

**Comment by raoufr** [comment]
@IlyaRadinsky this is a published package. How would the published package work with web?

**Comment by ghost** [comment]
@raoufr Regardless where we use it, it will need to be installed with npm/yarn and icons will be imported from it where needed.

**Comment by raoufr** [comment]
> @raoufr Regardless where we use it, it will need to be installed with npm/yarn and icons will be imported from it where needed.

Thank you @ajaybushel. That was not exactly my question. Was more asking whether building the package was going to change as a consequence of the new updates. I already spoke with @IlyaRadinsky and seems we don’t need to change anything in that respect. I will test and confirm this today.

**Review by nxame — APPROVED** [review]

**Review by raoufr — APPROVED** [review]

**Pull request merged**
