### PR TITLE
[dev] PBI AB#114211 [Back Office] Update Service Companion builder to use new Saddleback icons

### PR DESCRIPTION
**Pull request by IlyaRadinsky**

### CODE REVIEW

**Comment by raoufr** [comment]
@IlyaRadinsky are we planning on using these newly added icons on both the CA side and the Service Companion builder side? or just the CA side?

if the first, I don't think this will work since this is a react native library and we tried to access it before on the HC Admin client side and we were not successful.

**Comment by IlyaRadinsky** [comment]
@raoufr not sure if I know the answer for sure, but if these icons are going to be used on the CA side, then this PR makes sense.

**Comment by raoufr** [comment]
> @raoufr not sure if I know the answer for sure, but if these icons are going to be used on the CA side, then this PR makes sense.

@IlyaRadinsky understood, but the PBI referenced here is a Back Office client side I believe. So given that it might not make sense. Please correct me if I am wrong.

**Comment by nxame** [comment]
These same icons will be shown in widgets, browser and CA app.

**Comment by nxame** [comment]
@IlyaRadinsky These new icons have to be shown in the Back office builder as well. 
1. We will have to add these icons to the `react-cm-ui` as well. Probably: https://github.com/saddlebackdev/react-cm-ui/blob/dev/src/dataDisplay/icon/icon.jsx
2. And then update the dropdown in the builder: https://github.com/saddlebackdev/church-management/commits/dev/client/src/digitalProgram/builder/constants.ts

**Comment by ghost** [comment]
> if the first, I don't think this will work since this is a react native library and we tried to access it before on the HC Admin client side and we were not successful.

I dont understand, why did this not work on the HC Admin side? This is not specific to React Native. Its just a bunch of exported SVG files. I find it hard to understand why SVGs would not work on the browser.

The whole idea behind this package was to be able to have a single icons library for all our apps regardless the platform.

**Comment by IlyaRadinsky** [comment]
Better solution in #29

**Pull request closed without merging**
